services:
  backend:
    env_file:
      - ./backend/.env.prod  # Use the production environment variables
    environment:
      NODE_ENV: production
    ports:
      - "5001:5001"  # Expose backend on port 5001
    depends_on:
      db:
        condition: service_healthy

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongerpassword
      POSTGRES_DB: flightdb_prod  # Production database name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_prod:
    driver: local