name: Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Start Docker
      run: |
        sudo systemctl start docker

    - name: Build and Deploy with Docker Compose
      run: |
        docker compose --env-file ./backend/.env.${{ github.ref_name }} up -d --build
